# Generated by Django 3.0.7 on 2020-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20201221_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Fathername', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Education', models.TextField()),
                ('Experience', models.TextField()),
                ('DOB', models.DateField()),
                ('Linkdin', models.CharField(max_length=100)),
                ('Facebook', models.CharField(max_length=100)),
                ('Github', models.CharField(max_length=100)),
                ('Portfolio', models.TextField()),
                ('Profile', models.ImageField(null=True, upload_to='images/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Profiles',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
