# Generated by Django 3.0.7 on 2020-12-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile',
            new_name='Resume',
        ),
    ]
