# Generated by Django 3.0.7 on 2020-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20201224_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Fathername', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Skills', models.TextField()),
                ('Education', models.TextField()),
                ('Designation', models.CharField(max_length=100)),
                ('Experience', models.TextField()),
                ('DOB', models.DateField()),
                ('Mail', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Linkdin', models.CharField(max_length=100)),
                ('Facebook', models.CharField(max_length=100)),
                ('Github', models.CharField(max_length=100)),
                ('Portfolio', models.TextField()),
                ('Resume', models.ImageField(null=True, upload_to='images/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Resumes',
                'verbose_name_plural': 'Resume',
            },
        ),
    ]
