# Generated by Django 3.1.dev20200417182300 on 2020-12-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='resume',
            name='Resume',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
